name: Haskell CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "latest"
          working-directory: "./src"

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.10'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: src/
        fail-on: warning

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  build:
    needs: generate
    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
          stack-arguments: --stack-yaml ${{ matrix.stack-yaml }}
          test: false
  
  tests:
    needs: build

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4
 
    - name: Installing ollama
      uses: ai-action/ollama-action@v2
      with:
        model: gemma3:latest

    - name: Installing ollama
      uses: ai-action/ollama-action@v2
      with:
        model: qwen3:0.6b

    - name: Warming up ollama models
      run: |
        ollama run gemma3 "Hey, how are you?"
        ollama run qwen3:0.6b "Hey, how are you?"

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5

  # Run tests with multiple ollama versions
  ollama-versions:
    needs: tests
    name: tests with multiple ollama server versions
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ollama-versions: ["0.15.1", "0.14.3", "0.13.5"]
    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4
 
    - name: Installing ollama
      uses: ai-action/ollama-action@v2
      with:
        model: gemma3:latest
        version: ${{matrix.ollama-versions}}
    
    - name: Installing ollama
      uses: ai-action/ollama-action@v2
      with:
        model: qwen3:0.6b
        version: ${{matrix.ollama-versions}}
    
    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5

  build-examples:
    needs: tests

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
        working-directory: "./examples/ollama-example"
        test: false
