name: Haskell CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:

  only-merge-develop:
    runs-on: ubuntu-latest
    if : github.event_name == 'pull_request'
    steps:
      - name: Enforce develop-to-main merges
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" != "main" ]]; then
            echo "Pull request is not targeting main branch. Skipping checks."
            exit 0
          fi
          if [[ "${{ github.event.pull_request.head.ref }}" != "develop" ]]; then
            echo "Pull request is not from develop branch. Please merge develop into main."
            exit 1
          fi

  format:
    runs-on: ubuntu-latest
    needs: only-merge-develop
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "0.17.0.0"
          working-directory: "./src"

  hlint:
    runs-on: ubuntu-latest
    needs: only-merge-develop
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.10'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: src/
        fail-on: warning

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  build:
    needs: [generate, hlint, format]
    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
          stack-arguments: --stack-yaml ${{ matrix.stack-yaml }}
          test: false
  
  tests:
    needs: build

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4
 
    - name: Installing ollama
      uses: pydantic/ollama-action@v3
      with:
        model: gemma3:latest

    - name: Installing ollama
      uses: pydantic/ollama-action@v3
      with:
        model: qwen3:0.6b

    - name: Warming up ollama models
      run: |
        ollama run gemma3 "Hey, how are you?"
        ollama run qwen3:0.6b "Hey, how are you?"

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5

  build-examples:
    needs: tests

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
        working-directory: "./examples/ollama-example"
        test: false
